import expect from 'expect.js';

import querify from '../querify';

describe('querify()', () => {
  it('should return a string generated by received object', () => {
    expect(querify({
      github: 'axross',
      twitter: 'axross_',
      website: 'http://axross.me/',
    })).to.be(
      '?github=axross&twitter=axross_&website=http%3A%2F%2Faxross.me%2F'
    );

    expect(querify({
      role: 'Software Engineer',
    })).to.be(
      '?role=Software%20Engineer'
    );
  });

  it('should return an empty string when that receive empty object', () => {
    expect(querify({})).to.be('');
  });
});
