import expect from 'expect.js';

import _ from '../util';

describe('util', () => {
  describe('queryString()', () => {
    it('should return a string generated by received object', () => {
      expect(_.queryString({
        github: 'axross',
        twitter: 'axross_',
        website: 'http://axross.me/',
      })).to.be(
        '?github=axross&twitter=axross_&website=http%3A%2F%2Faxross.me%2F'
      );

      expect(_.queryString({
        role: 'Software Engineer',
      })).to.be(
        '?role=Software%20Engineer'
      );
    });

    it('should return an empty string when that receive empty object', () => {
      expect(_.queryString({})).to.be('');
    });
  });
});
